spring:
  profiles:
    active: dev   # profil par dÃ©faut

---

spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: "Bienvenue sur l'environnement DEV !ğŸš€"

---

spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: "Bienvenue sur l'environnement PROD! ğŸ­"
